services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "pip install --upgrade pip &&
             pip install -r requirements.txt &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://langchain:langchain@db:5432/langchain

  db:
    image: pgvector/pgvector:0.8.0-pg16
    environment:
      POSTGRES_DB: langchain
      POSTGRES_USER: langchain
      POSTGRES_PASSWORD: langchain
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
